### PR TITLE
Fix: Update Modal ConfirmLabel Logic for Transaction Types - 2789

### LINKED ISSUE #2789: TFRS - wrong labels showing in confirmation modal window when analyst recommends recording a transfer
**Describe the Bug**
The wrong labels are showing in the confirmation modal window when the gov't analyst recommends recording a transfer within the TFRS January release, dev environment. 

The modal window currently says "Are you sure you want to recommend issuance of compliance units for this transfer?" and then includes a button label of "Recommend issuance". 

The modal window should say, "Are you sure you want to recommend recording this transfer?" and the button label should say "Recommend recording transfer". 

**Screenshot of current labels:**

**Implications**
Wrong labels in January release

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: IDIR user; Gov't analyst role; TFRS Jan release, dev env
1. Go to the Transaction page
2. Click on a Transfer with the Submitted status
3. Click on the Recommend recording transfer button

**Other considerations:**
As a FYI, the New Initiative Agreement Issuance feature (formerly New Part 3 Award) uses similar language in the confirmation modal window when the analyst is recommending the approval of an issuance from an Initiative Agreement. The language in this area of TFRS is correct. There may be some connections between the language used here and the language used in the confirmation modal window for transfers (the issue above). Please ensure that fixing the language for transfers does not change the language in used in the modal window for the New Initiative Agreement Issuance feature. 

This feature can be accessed by an IDIR user with the Gov't analyst role by going to the File Submissions page and then clicking on the 'New Initiative Agreement Issuance' button near the top of the page. 

Screenshot:

### PR DESCRIPTION
**Pull request by hamed-valiollahi**
This PR addresses the issue where the modal's `confirmLabel` was not dynamically updating based on different transaction types.

Closes #2789

### CODE REVIEW

File: frontend/src/credit_transfers/CreditTransferViewContainer.js [hunk 1]
```diff
@@ -517,19 +517,27 @@ class CreditTransferViewContainer extends Component {
   }
 
   _modalRecommend (item) {
+    const isBuyOrSell = [CREDIT_TRANSFER_TYPES.buy.id, CREDIT_TRANSFER_TYPES.sell.id].indexOf(item.type.id) >= 0;
```
Comment (AlexZorkin) [inline frontend/src/credit_transfers/CreditTransferViewContainer.js:520]: I don't think we need to differentiate between Buy or Sell because the button labels should be the same for both. Is this component even used for Initiative Agreements?

Comment (hamed-valiollahi) [reply frontend/src/credit_transfers/CreditTransferViewContainer.js:520]: Yes, this modal is used for "Transfers with the Submitted Status" as well as for "Initiative Agreements".
Please check out Justin's comment on the [ticket page](https://app.zenhub.com/workspaces/low-carbon-fuel-standard-644c2db3be098a001977ad0b/issues/gh/bcgov/tfrs/2789) for more information.

Comment (AlexZorkin) [reply frontend/src/credit_transfers/CreditTransferViewContainer.js:520]: ah gotcha, thanks.

**Review by AlexZorkin — APPROVED** [review]

File: frontend/src/credit_transfers/CreditTransferViewContainer.js (hunk 1 above)
Comment (hamed-valiollahi) [reply frontend/src/credit_transfers/CreditTransferViewContainer.js:520]: You're welcome!
Thanks, Alex, for reviewing my PR.
